/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.api.tasks.compile.JavaCompile

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.graalvm.native)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(project(":core"))
    implementation(project(":engines"))
    annotationProcessor(libs.picocli.codegen)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly(libs.junit.platform.launcher)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.picocli)
    implementation(libs.jackson.databind)
}

application {
    // Define the main class for the application.
    mainClass = "com.omaarr90.statecraft.StatecraftCli"
    applicationDefaultJvmArgs = listOf("--enable-preview", "--add-modules", "jdk.incubator.vector")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    jvmArgs("--enable-preview", "--add-modules", "jdk.incubator.vector")
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.addAll(
            listOf(
                    "--enable-preview",
                    "--add-modules",
                    "jdk.incubator.vector",
                    "-Aproject=${project.group}/${project.name}"))
}

graalvmNative {
    binaries {
        named("main") {
            imageName.set("statecraft")
            resources.autodetect()
        }
    }
}
